- username: admin
  hashed_password: :$2y$05$8eqyIthlK5fls9QGuRewt.MakjCscvPYsm3a1q/UED0G1vxeNztSu
  api_key: "admin_api_key"
  workspaces: [] # has access to all workspaces and datasets
- username: kalyan
  hashed_password: $2y$05$lidTepfiK94fpJNbAiB6M.DmB.1S/n6mTMcwegTBHhxcSl3u2u9V6
  api_key: "kalyan_api_key"
  workspaces: ["gst", "gst_dev"]
- username: henry
  hashed_password: $2y$05$FqH/CAZKbTbX/pBLDqcVAeX8Rojsi7L.D7PcvMTldhkJb02Gn5jd2
  api_key: "henry_api_key"
  workspaces: ["gst", "gst_dev"]
- username: sarah
  hashed_password: $2y$05$ogv9KwnBMBzrWxiiBA8w4.omasGC9QYhAkZJNPFpByPI.NtWnxBPK
  api_key: "sarah_api_key"
  workspaces: ["gst"]
- username: michal
  hashed_password: $2y$05$DeL0yJY50yCKcwQUq8gtueixcRTxUHxYPHd8avQbVCuBNSdXYGDdi
  api_key: "michal_api_key"
  workspaces: ["gst"]
- username: matyas
  hashed_password: :$2y$05$9Jh6G16GziSfTo8i9vCC9e83Up.s3q1JNcS7vEC3JZ2vDlmmluRv6
  api_key: "matyas_api_key"
  workspaces: [] # has access to all workspaces and datasets
