theme: jekyll-theme-minimal
title: Climate Policy Radar – Global Stocktake Explorer
description: Climate Policy Radar's work for the UNFCCC Global Stocktake
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one