name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set git config to use personal access token in secrets
        run: |
          git config --global url."https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/climatepolicyradar/explorer.git".insteadOf "https://github.com/climatepolicyradar/explorer.git"
  
      - name: Install dependencies
        run: |
          python -m pip install "poetry==1.2.2" && poetry install
          
      - name: Run test suite
        run: |
          poetry run python -m pytest \
          --nbmake-find-import-errors \
          --nbmake-timeout=20 -vvv